services:
  - type: web
    name: meserito-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Estas variables las configuras manualmente en Render Dashboard:
      # MONGODB_URI: tu_mongodb_atlas_connection_string
      # JWT_SECRET: tu_jwt_secret_super_seguro
      # SALTOS_BCRYPT: 12
      # SENDGRID_API_KEY: tu_sendgrid_api_key (opcional) 